
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sequences](
	[RunNumber] [int] IDENTITY(1,1) NOT NULL,
	[SequenceType] [tinyint] NOT NULL,
	[SequenceLength] [int] NOT NULL,
	[MaxElement] [bigint] NOT NULL,
	[Average] [float] NOT NULL,
 CONSTRAINT [PK_Sequences] PRIMARY KEY CLUSTERED 
(
	[RunNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


